config/routes.rb
Rails.application.routes.draw do
  get 'cardapio/index'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :clients, only: %i[create]
  resources :cardapios, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cardapio.rb
class Cardapio < ApplicationRecord
  validates :nome, presence: true
end

app/models/client.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ URI::MailTo::EMAIL_REGEXP
      record.errors.add attribute, (options[:message] || "is not an email")
    end
  end
end

class Client < ApplicationRecord
  validates :nome, :email, :telefone, :mensagem, presence: true
  validates :email, :telefone, uniqueness: true
  validates :email, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cardapios_controller.rb
class CardapiosController < ApplicationController
  def index
    @cardapios = Cardapio.all
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    redirect_to root_path if @client.save
  end

  private

  def client_params
    params.require(:client).permit(:nome, :email, :telefone, :mensagem)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @client = Client.new(client_params)
  end

  def client_params
    params.permit(:nome, :email, :telefone, :mensagem)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cardapios/index.html.erb
<div class="container mt-3 pt-5">
  <div class="row">
    <div class="col-1 col-sm col-lg"></div>
    <div class="col-10 col-sm-8 col-lg-6">
      <%= image_tag "sirenalogoazul.png", style:"height: auto; width:100%;", id:"logobranca"%>
    </div>
    <div class="col-1 col-sm col-lg"></div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-12 mt-3 col-lg-6">
      <%= link_to (image_tag 'sirenacardapio1.jpg', style:"height: auto; width:100%; box-shadow: 0 0 5px black;"), "/sirenacardapio.pdf", target:"_blank"%>
    </div>
    <div class="col-12 mt-3 col-lg-6">
       <a href="https://api.whatsapp.com/send?1=pt_BR&phone=552233016288" target="_blank">
        <%= image_tag "sirenafaleconosco.jpg", style:"height: auto; width:100%; box-shadow: 0 0 5px black;"%>
      </a>
    </div>
    <div class="col-12 mt-3 col-lg-6">
      <a href="https://www.google.com/maps/place/Sirena+B%C3%BAzios+Gastrobar/@-22.7696835,-41.9119599,15z/data=!4m5!3m4!1s0x0:0x60f20f24c43c0e4f!8m2!3d-22.7696835!4d-41.9119599" target="_blank">
        <%= image_tag "sirenaondeestamos.jpg", style:"height: auto; width:100%; box-shadow: 0 0 5px black;"%>
      </a>
   </div>
   <div class="col-12 mt-3 col-lg-6">
      <a href="https://cutt.ly/gKDI3OH" target="_blank">
        <%= image_tag "sirenawaze.jpg", style:"height: auto; width:100%; box-shadow: 0 0 5px black;"%>
      </a>
   </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIRENABuzios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <style>

    @import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Playfair+Display:wght@400;700&family=Roboto:wght@400;700&display=swap');

    @media screen and (max-width: 1100px) {
      .topnav a:not(:first-child) {display: none;}
      .topnav a.icon {
        float: right;
        display: block;
      }
    }

    @media screen and (max-width: 1100px) {
      .topnav.responsive {position: relative;}
      .topnav.responsive .icon {
        position: absolute;
        right: 0;
        top: 0;
      }
      .topnav.responsive a {
        float: none;
        display: block;
        text-align: left;
      }
    }
    </style>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

    <meta name="facebook-domain-verification" content="0av9760u8lzjkt8fjqwb6fwq9l7y5i" />

    <!-- Meta Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '441423044557167');
    fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=441423044557167&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Meta Pixel Code -->
  </head>

  <body>
    <div style="position: relative">
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
    <script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "topnav") {
        x.className += " responsive";
      } else {
        x.className = "topnav";
      }
    }
    </script>
  </body>

  <script>
    AOS.init();
  </script>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2 )), url('<%= image_path "bannerdia.jpg" %>');">
  <%= render 'shared/navbar' %>
  <div class="container banner-logo mt-5 pt-5">
    <div class="row" style="width:100vw;">
      <div class="col-1 col-sm-3 col-lg"></div>
      <div class="col-10 col-sm-6 col-lg-3">
        <%= image_tag "sirenalogobranco.png", style:"height: auto; width:100%;", id:"logobranca"%>
      </div>
      <div class="col-1 col-sm-3 col-lg"></div>
    </div>
  </div>
</div>

<div class="container" id="quemsomos">
  <div class="row">
    <div class="banner-dj my-5" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= image_path "palmeirasbanner.jpg" %>');">
      <div class="col-0 col-lg-0"></div>
      <div class="col-12 col-lg-12 my-4">
        <h1 class="titles"><strong>QUEM SOMOS</strong></h1>
        <p style="font-size: 18px; text-align:center; color: #315572;">O Sirena Búzios é um Gastrobar na beira da praia de Manguinhos, em frente ao pôr do sol mais lindo da cidade! Totalmente inspirados na natureza que nos cerca, nossa proposta é oferecer excelente música e gastronomia em um ambiente informal, onde amigos e famílias podem desfrutar de uma experiência incrível e com o pé na areia.</p>
      </div>
      <div class="col-0 col-lg-0"></div>
    </div>
  </div>
</div>

<div class="container" style="margin-bottom: 130px;">
  <div class="row">
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "drink3.jpg" %>');" data-aos="fade-up">
      </div>
    </div>
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "vista1.jpg" %>');" data-aos="fade-up">
      </div>
    </div>
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "drink2.jpg" %>');" data-aos="fade-up">
      </div>
   </div>
  </div>
</div>

<div class="container" id="sunset">
  <div class="banner-dj my-5" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= image_path "palmeirasbanner.jpg" %>');">
    <div class="row">
      <div class="col-0 col-lg-0"></div>
      <div class="col-12 col-lg-12 my-4">
        <h1 class="titles"><strong>SUNSET</strong></h1>
        <p style="font-size: 20px; text-align:center; color: #315572;">Todos os dias a partir das 16h nossos Djs agitam o pôr-do-sol mais lindo de Búzios na areia do Sirena, deixando nossa atmosfera ainda mais agradável e especial.</p>
        <h1 class="lineup mt-5" style="font-size: 30px; text-align:center; color: #223748;"><strong>LINE UP</strong></h1>
        <p style="font-size: 20px; text-align:center; margin-right:10px; color: #315572;">Djs residentes Robert Pantoja e Warley Santos</p>
      </div>
      <div class="col-0 col-lg-0"></div>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "drink1.jpg" %>');" data-aos="fade-up">
      </div>
    </div>
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "djsirena.png" %>');" data-aos="fade-up">
      </div>
    </div>
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "drink6.jpg" %>');" data-aos="fade-up">
      </div>
   </div>
  </div>
</div>

<div class="container mt-5" style="margin-bottom: 130px;">
  <div class="video-wrapper">
    <iframe src="https://www.youtube.com/embed/eiYlhE-CQxg" title="Sirena Buzios Sunset" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>

<div class="container mt-5" id="eventos">
  <div class="banner-dj my-5" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= image_path "palmeirasbanner.jpg" %>');">
    <div class="row mb-2">
      <div class="col-0 col-lg-"></div>
      <div class="col-12 col-lg-10" style="align-items: center; justify-content: center; display: flex;">
         <h1 class="titles"><strong>SUA FESTA NO</strong></h1>
      </div>
      <div class="col-12 col-lg-1" style="align-items: center; justify-content: center; display: flex;">
        <%= image_tag "sirenalogoazul.png", style:"height: 120px; width:120px; margin-left: 10px; margin-bottom:15px"%>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5" style="margin-bottom: 100px;" data-aos="zoom-in">
  <div class="banner-eventos" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2 )), url('<%= image_path "estruturasirena.jpg" %>');">
    <div class="container banner-logo">
      <div class="row mt-2"></div>
      <div class="row" style="height: auto; width:100%;">
        <div class="col-2 col-sm col-lg"></div>
        <div class="col-9 col-sm-5 col-lg-3" style="z-index:2;">
          <%= image_tag "cardestrutura.png", style:"height: auto; width:100%;  border-radius: 4px; box-shadow: 0 0 5px black; "%>
        </div>
        <div class="col-1 col-sm col-lg"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-sm-12 col-lg-6">
      <div class="banner-eventos mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2 )), url('<%= image_path "evento3.jpg" %>');">
      </div>
    </div>
    <div class="col-12 col-sm-12 col-lg-6">
      <div class="banner-eventos mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2 )), url('<%= image_path "estruturasirena1.png" %>');">
        <div class="container banner-logo">
          <div class="row my-5"></div>
          <div class="row" style="height: auto; width:100%;">
            <div class="col-2 col-sm col-lg"></div>
            <div class="col-9 col-sm-5 col-lg-6">
              <%= image_tag "cardestrutura1.png", style:"height: auto; width:100%;  border-radius: 4px; box-shadow: 0 0 5px black; "%>
            </div>
            <div class="col-1 col-sm col-lg"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "evento4.png" %>');">
      </div>
    </div>
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "evento2.jpg" %>');">
      </div>
    </div>
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "evento1.jpg" %>');">
      </div>
   </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="banner-dj my-5" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= image_path "palmeirasbanner.jpg" %>');">
      <div class="col-0 col-lg-0"></div>
      <div class="col-12 col-lg-12 mt-4">
        <%= link_to "CARDÁPIO", cardapios_path, class:"titles", style: "font-weight: bold;" %>
        <p style="font-size: 23px; text-align:center; color: #315572;">Clique para ver os melhores pratos e drinks à beira-mar de Búzios</p>
      </div>
      <div class="col-0 col-lg-0"></div>
    </div>
  </div>
</div>

<div class="container mb-5">
  <div class="row">
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "prato3.jpg" %>');" data-aos="zoom-in">>
      </div>
    </div>
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "prato9.jpg" %>');" data-aos="zoom-in">>
      </div>
    </div>
    <div class="col-12 mt-3 col-lg-4">
      <div class="card-category" style="background-image: url('<%= image_path "prato8.jpg" %>');" data-aos="zoom-in">>
      </div>
    </div>
  </div>
</div>

<div class="banner-sunset" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2 )), url('<%= image_path "bannersunset.jpg" %>');">
  <div class="container banner-logo mt-5 pt-5">
    <div class="row my-5"></div>
    <div class="row" style="width:100vw;">
      <div class="col-1 col-sm-3 col-lg"></div>
      <div class="col-10 col-sm-6 col-lg-3">
        <%= image_tag "sirenalogobranco.png", style:"height: auto; width:100%;", id:"logobranca"%>
      </div>
      <div class="col-1 col-sm-3 col-lg"></div>
    </div>
  </div>
</div>

<div class="container my-5">
  <div class="row">
    <div class="col-12 col-lg-7 mt-4 me-5">
      <div id='map' style='width: 100%; height: 550px; border-radius: 4px; box-shadow: 0 0 5px black;' class= "mt-3"></div>
    </div>
    <div class="col-12 col-lg-4 form-style mt-5">
      <!-- Insert form here -->
      <%= render 'shared/form' %>
      <hr>
      <h2>CADASTRE-SE PARA RESERVAS E PROMOÇÕES EXCLUSIVAS</h2>
    </div>
  </div>
</div>



<style>
#marker {
background-image: url('<%= image_path 'marker.png' %>');
background-size: cover;
width: 40px;
height: 55px;
border-radius: 50%;
cursor: pointer;
}

.mapboxgl-popup {
max-width: 200px;
}
</style>

<script>
	mapboxgl.accessToken = 'pk.eyJ1Ijoibmlja3NmYXJpYXMiLCJhIjoiY2wzNHN3NWdqMDAxNTNjcWI4cjVmOXNlbSJ9.-kHJJZfflrU2tAKpm7L75w';
const monument = [-41.91201198021214, -22.769525662110265];
const map = new mapboxgl.Map({
container: 'map',
style:'mapbox://styles/mapbox/streets-v11',
center: monument,
zoom: 15
});

// create the popup
const popup = new mapboxgl.Popup({ offset: 25 }).setText(
'Sirena Buzios - Associação dos Pescadores - Av. José Bento Ribeiro Dantas, 85'
);

// create DOM element for the marker
const el = document.createElement('div');
el.id = 'marker';



// create the marker
const marker = new mapboxgl.Marker(el)
.setLngLat(monument)
.setPopup(popup) // sets a popup on this marker
.addTo(map);

const markerDiv = marker.getElement();
markerDiv.addEventListener('mouseenter', () => marker.togglePopup());
markerDiv.addEventListener('mouseleave', () => marker.togglePopup());
</script>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start text-white mt-5" id="footer">
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Nos siga e avalie nas nossas redes sociais: <i class="fas fa-heart"></i> </span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="https://www.facebook.com/sirenabuzios" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="https://www.google.com/search?q=sirena+buzios&oq=sirena+buzios&aqs=chrome..69i57j46i175i199i512j0i22i30l3j69i60l3.2051j0j7&sourceid=chrome&ie=UTF-8" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="https://www.instagram.com/sirenabuzios/" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="https://www.tripadvisor.com.br/Restaurant_Review-g303492-d19917882-Reviews-Sirena_Buzios_Gastrobar-Armacao_dos_Buzios_State_of_Rio_de_Janeiro.html" class="me-4 text-reset">
        <i class="fab fa-tripadvisor"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            sirena búzios gastrobar
          </h6>
          <p>
          Associação dos Pescadores - Av. José Bento Ribeiro Dantas, 85, Manguinhos.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contato
          </h6>
          <p><i class="fas fa-home me-3"></i> Armação do Búzios, RJ, Brasil</p>
          <p>
            <a href="https://api.whatsapp.com/send?1=pt_BR&phone=552233016288" class="me-4 text-reset">
            <i class="fa fa-whatsapp me-3"></i>
            +55 (22) 3301-6288
          </p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center" style="background-color: rgba(0, 0, 0, 0.05);">
    <div class="avatar-perfil d-flex justify-content-center align-items-center" style="position: relative">
       <p>© Sirenabuzios.com was made by: <a href="https://github.com/PBuenolima" target=”_blank”>
       <img src="https://avatars.githubusercontent.com/u/101818151?s=40&v=4"></a>
       <a href="https://github.com/nickolasfarias" target=”_blank”>
       <img src="https://avatars.githubusercontent.com/u/85416366?v=4"></a>
    </div>
  </div>


  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_form.html.erb
      <%= simple_form_for @client  do |f| %>
        <%= f.input :nome %>
        <%= f.input :email %>
        <%= f.input :telefone %>
        <%= f.input :mensagem %>
        <%= f.submit "ENVIAR", class: "btn btn-color"%>
      <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-sirena d-flex align-itens-center justify-content-center">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <div class="topnav" id="myTopnav">
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
      <i class="fa fa-bars"></i>
    </a>
    <a href="#quemsomos">QUEM SOMOS</a>
    <a href="#sunset">SUNSET</a>
    <a href="#eventos">EVENTOS</a>
    <%= link_to "CARDAPIO", cardapios_path %>
    <a href="https://api.whatsapp.com/send?1=pt_BR&phone=552233016288" target="_blank">FALE CONOSCO</a>
    <a href="https://www.google.com/maps/place/Sirena+B%C3%BAzios+Gastrobar,+Associa%C3%A7%C3%A3o+dos+Pescadores+-+Av.+Jos%C3%A9+Bento+Ribeiro+Dantas,+85+-+box+7,+B%C3%BAzios+-+RJ,+28950-000/@-22.7696835,-41.9119599,15z/data=!4m2!3m1!1s0x9701b3a2e4add5:0x60f20f24c43c0e4f" target="_blank">ONDE ESTAMOS</a>
  </div>
</div>